api.py:23 - 2024-08-26 17:03:59,996 - ERROR - Error while user registration module 'uuid' has no attribute 'UUID4'
api.py:23 - 2024-08-26 17:04:39,883 - ERROR - Error while user registration 'User_v2' object does not support item assignment
service.py:23 - 2024-08-26 17:19:17,667 - INFO - User Register Successfully {'id': UUID('3fa85f64-5717-4562-b3fc-2c963f66afa6'), 'username': 'harshk', 'firstname': 'Harshal', 'lastname': 'Kharabe', 'email': 'harsh@k.com', 'phone_no': 'string', 'password': 'string', 'is_logged_in': 'string'}
service.py:23 - 2024-08-26 17:19:17,667 - INFO - User Register Successfully {'id': UUID('3fa85f64-5717-4562-b3fc-2c963f66afa6'), 'username': 'harshk', 'firstname': 'Harshal', 'lastname': 'Kharabe', 'email': 'harsh@k.com', 'phone_no': 'string', 'password': 'string', 'is_logged_in': 'string'}
service.py:23 - 2024-08-26 17:20:42,144 - INFO - User Register Successfully id=UUID('3fa85f64-5717-4562-b3fc-2c963f66afa6') username='harshk' firstname='Harshal' lastname='Kharabe' email='harsh@k.com' phone_no='string' password='string' is_logged_in='string'
service.py:23 - 2024-08-26 17:20:42,144 - INFO - User Register Successfully id=UUID('3fa85f64-5717-4562-b3fc-2c963f66afa6') username='harshk' firstname='Harshal' lastname='Kharabe' email='harsh@k.com' phone_no='string' password='string' is_logged_in='string'
service.py:23 - 2024-08-26 17:22:27,913 - INFO - User Register Successfully id=UUID('3fa85f64-5717-4562-b3fc-2c963f66afa6') username='harshk' firstname='Harshal' lastname='Kharabe' email='harsh@k.com' phone_no='string' password='string' is_logged_in='string'
service.py:23 - 2024-08-26 17:22:27,913 - INFO - User Register Successfully id=UUID('3fa85f64-5717-4562-b3fc-2c963f66afa6') username='harshk' firstname='Harshal' lastname='Kharabe' email='harsh@k.com' phone_no='string' password='string' is_logged_in='string'
service.py:23 - 2024-08-26 17:23:35,924 - INFO - User Register Successfully id=UUID('3fa85f64-5717-4562-b3fc-2c963f66afa6') username='aniketpaa' firstname='Aniket' lastname='Bhudke' email='ani@pa.com' phone_no='1122112212' password='omgpa' is_logged_in='string'
service.py:23 - 2024-08-26 17:23:35,924 - INFO - User Register Successfully id=UUID('3fa85f64-5717-4562-b3fc-2c963f66afa6') username='aniketpaa' firstname='Aniket' lastname='Bhudke' email='ani@pa.com' phone_no='1122112212' password='omgpa' is_logged_in='string'
service.py:24 - 2024-08-26 17:24:06,968 - INFO - User Register Successfully id=UUID('ccf5c4a1-8a99-4e71-9951-5391453e230e') username='aniketpaa' firstname='Aniket' lastname='Bhudke' email='ani@pa.com' phone_no='1122112212' password='omgpa' is_logged_in='string'
service.py:24 - 2024-08-26 17:24:06,968 - INFO - User Register Successfully id=UUID('ccf5c4a1-8a99-4e71-9951-5391453e230e') username='aniketpaa' firstname='Aniket' lastname='Bhudke' email='ani@pa.com' phone_no='1122112212' password='omgpa' is_logged_in='string'
service.py:24 - 2024-08-30 22:43:51,321 - INFO - User Register Successfully id=UUID('4ebbd66c-b257-4427-8589-a81a25456856') username='string' firstname='string' lastname='string' email='user@example.com' phone_no='string' password='string' is_logged_in='string'
service.py:24 - 2024-08-30 22:43:51,321 - INFO - User Register Successfully id=UUID('4ebbd66c-b257-4427-8589-a81a25456856') username='string' firstname='string' lastname='string' email='user@example.com' phone_no='string' password='string' is_logged_in='string'
service.py:29 - 2024-08-30 22:57:17,210 - ERROR - Error : Class 'src.authentication.auth_models.model.User_v2' is not mapped
service.py:29 - 2024-08-30 22:57:17,210 - ERROR - Error : Class 'src.authentication.auth_models.model.User_v2' is not mapped
service.py:28 - 2024-08-30 22:57:40,945 - ERROR - Error : Class 'src.authentication.auth_models.model.User_v2' is not mapped
service.py:28 - 2024-08-30 22:57:40,945 - ERROR - Error : Class 'src.authentication.auth_models.model.User_v2' is not mapped
service.py:28 - 2024-08-30 22:59:14,757 - ERROR - Error : Class 'src.authentication.auth_models.model.User_v2' is not mapped
service.py:28 - 2024-08-30 22:59:14,757 - ERROR - Error : Class 'src.authentication.auth_models.model.User_v2' is not mapped
service.py:28 - 2024-08-30 22:59:39,202 - ERROR - Error : (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

(Background on this error at: https://sqlalche.me/e/14/e3q8)
service.py:28 - 2024-08-30 22:59:39,202 - ERROR - Error : (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

(Background on this error at: https://sqlalche.me/e/14/e3q8)
service.py:28 - 2024-08-30 23:01:51,927 - ERROR - Error : (psycopg2.errors.UndefinedTable) relation "user" does not exist
LINE 1: INSERT INTO "user" (id, username, firstname, lastname, email...
                    ^

[SQL: INSERT INTO "user" (id, username, firstname, lastname, email, phone_no, password, is_logged_in) VALUES (%(id)s, %(username)s, %(firstname)s, %(lastname)s, %(email)s, %(phone_no)s, %(password)s, %(is_logged_in)s)]
[parameters: {'id': UUID('816fbcfe-21e5-4fd4-ba7c-c8fca5761c02'), 'username': 'kunalaswar', 'firstname': 'Kunal', 'lastname': 'Aswar', 'email': 'kun@al.com', 'phone_no': 'string', 'password': 'ku@nl', 'is_logged_in': 'string'}]
(Background on this error at: https://sqlalche.me/e/14/f405)
service.py:28 - 2024-08-30 23:01:51,927 - ERROR - Error : (psycopg2.errors.UndefinedTable) relation "user" does not exist
LINE 1: INSERT INTO "user" (id, username, firstname, lastname, email...
                    ^

[SQL: INSERT INTO "user" (id, username, firstname, lastname, email, phone_no, password, is_logged_in) VALUES (%(id)s, %(username)s, %(firstname)s, %(lastname)s, %(email)s, %(phone_no)s, %(password)s, %(is_logged_in)s)]
[parameters: {'id': UUID('816fbcfe-21e5-4fd4-ba7c-c8fca5761c02'), 'username': 'kunalaswar', 'firstname': 'Kunal', 'lastname': 'Aswar', 'email': 'kun@al.com', 'phone_no': 'string', 'password': 'ku@nl', 'is_logged_in': 'string'}]
(Background on this error at: https://sqlalche.me/e/14/f405)
service.py:28 - 2024-08-30 23:11:41,041 - ERROR - Error : (psycopg2.errors.UndefinedTable) relation "user" does not exist
LINE 1: INSERT INTO "user" (id, username, firstname, lastname, email...
                    ^

[SQL: INSERT INTO "user" (id, username, firstname, lastname, email, phone_no, password, is_logged_in) VALUES (%(id)s, %(username)s, %(firstname)s, %(lastname)s, %(email)s, %(phone_no)s, %(password)s, %(is_logged_in)s)]
[parameters: {'id': UUID('2aef06ef-bec1-41ce-a0cc-90e638e59dce'), 'username': 'kunalaswar', 'firstname': 'Kunal', 'lastname': 'Aswar', 'email': 'kun@al.com', 'phone_no': 'string', 'password': 'ku@nl', 'is_logged_in': 'string'}]
(Background on this error at: https://sqlalche.me/e/14/f405)
service.py:28 - 2024-08-30 23:11:41,041 - ERROR - Error : (psycopg2.errors.UndefinedTable) relation "user" does not exist
LINE 1: INSERT INTO "user" (id, username, firstname, lastname, email...
                    ^

[SQL: INSERT INTO "user" (id, username, firstname, lastname, email, phone_no, password, is_logged_in) VALUES (%(id)s, %(username)s, %(firstname)s, %(lastname)s, %(email)s, %(phone_no)s, %(password)s, %(is_logged_in)s)]
[parameters: {'id': UUID('2aef06ef-bec1-41ce-a0cc-90e638e59dce'), 'username': 'kunalaswar', 'firstname': 'Kunal', 'lastname': 'Aswar', 'email': 'kun@al.com', 'phone_no': 'string', 'password': 'ku@nl', 'is_logged_in': 'string'}]
(Background on this error at: https://sqlalche.me/e/14/f405)
service.py:28 - 2024-08-30 23:12:55,131 - ERROR - Error : (psycopg2.errors.UndefinedTable) relation "user" does not exist
LINE 1: INSERT INTO "user" (id, username, firstname, lastname, email...
                    ^

[SQL: INSERT INTO "user" (id, username, firstname, lastname, email, phone_no, password, is_logged_in) VALUES (%(id)s, %(username)s, %(firstname)s, %(lastname)s, %(email)s, %(phone_no)s, %(password)s, %(is_logged_in)s)]
[parameters: {'id': UUID('39f9056f-2ab2-48b9-b8f6-bfc488c883e8'), 'username': 'kunalaswar', 'firstname': 'Kunal', 'lastname': 'Aswar', 'email': 'kun@al.com', 'phone_no': 'string', 'password': 'ku@nl', 'is_logged_in': 'string'}]
(Background on this error at: https://sqlalche.me/e/14/f405)
service.py:28 - 2024-08-30 23:12:55,131 - ERROR - Error : (psycopg2.errors.UndefinedTable) relation "user" does not exist
LINE 1: INSERT INTO "user" (id, username, firstname, lastname, email...
                    ^

[SQL: INSERT INTO "user" (id, username, firstname, lastname, email, phone_no, password, is_logged_in) VALUES (%(id)s, %(username)s, %(firstname)s, %(lastname)s, %(email)s, %(phone_no)s, %(password)s, %(is_logged_in)s)]
[parameters: {'id': UUID('39f9056f-2ab2-48b9-b8f6-bfc488c883e8'), 'username': 'kunalaswar', 'firstname': 'Kunal', 'lastname': 'Aswar', 'email': 'kun@al.com', 'phone_no': 'string', 'password': 'ku@nl', 'is_logged_in': 'string'}]
(Background on this error at: https://sqlalche.me/e/14/f405)
service.py:28 - 2024-08-30 23:22:51,959 - ERROR - Error : (psycopg2.errors.UndefinedTable) relation "user" does not exist
LINE 1: INSERT INTO "user" (id, username, firstname, lastname, email...
                    ^

[SQL: INSERT INTO "user" (id, username, firstname, lastname, email, phone_no, password, is_logged_in) VALUES (%(id)s, %(username)s, %(firstname)s, %(lastname)s, %(email)s, %(phone_no)s, %(password)s, %(is_logged_in)s)]
[parameters: {'id': UUID('b24a63c8-3ff4-4f61-b9d1-6e5ba3a85ad3'), 'username': 'string', 'firstname': 'string', 'lastname': 'string', 'email': 'user@example.com', 'phone_no': 'string', 'password': 'string', 'is_logged_in': 'string'}]
(Background on this error at: https://sqlalche.me/e/14/f405)
service.py:28 - 2024-08-30 23:22:51,959 - ERROR - Error : (psycopg2.errors.UndefinedTable) relation "user" does not exist
LINE 1: INSERT INTO "user" (id, username, firstname, lastname, email...
                    ^

[SQL: INSERT INTO "user" (id, username, firstname, lastname, email, phone_no, password, is_logged_in) VALUES (%(id)s, %(username)s, %(firstname)s, %(lastname)s, %(email)s, %(phone_no)s, %(password)s, %(is_logged_in)s)]
[parameters: {'id': UUID('b24a63c8-3ff4-4f61-b9d1-6e5ba3a85ad3'), 'username': 'string', 'firstname': 'string', 'lastname': 'string', 'email': 'user@example.com', 'phone_no': 'string', 'password': 'string', 'is_logged_in': 'string'}]
(Background on this error at: https://sqlalche.me/e/14/f405)
service.py:28 - 2024-08-30 23:25:51,584 - ERROR - Error : (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type boolean: "string"
LINE 1: ...Kharabe', 'harsh@k.com', '1234554321', 'hkharabe', 'string')
                                                              ^

[SQL: INSERT INTO "user" (id, username, firstname, lastname, email, phone_no, password, is_logged_in) VALUES (%(id)s, %(username)s, %(firstname)s, %(lastname)s, %(email)s, %(phone_no)s, %(password)s, %(is_logged_in)s)]
[parameters: {'id': UUID('309ee7dd-c2b7-4058-8480-58a6243b5d61'), 'username': 'harshalkharabe', 'firstname': 'Harshal', 'lastname': 'Kharabe', 'email': 'harsh@k.com', 'phone_no': '1234554321', 'password': 'hkharabe', 'is_logged_in': 'string'}]
(Background on this error at: https://sqlalche.me/e/14/9h9h)
service.py:28 - 2024-08-30 23:25:51,584 - ERROR - Error : (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type boolean: "string"
LINE 1: ...Kharabe', 'harsh@k.com', '1234554321', 'hkharabe', 'string')
                                                              ^

[SQL: INSERT INTO "user" (id, username, firstname, lastname, email, phone_no, password, is_logged_in) VALUES (%(id)s, %(username)s, %(firstname)s, %(lastname)s, %(email)s, %(phone_no)s, %(password)s, %(is_logged_in)s)]
[parameters: {'id': UUID('309ee7dd-c2b7-4058-8480-58a6243b5d61'), 'username': 'harshalkharabe', 'firstname': 'Harshal', 'lastname': 'Kharabe', 'email': 'harsh@k.com', 'phone_no': '1234554321', 'password': 'hkharabe', 'is_logged_in': 'string'}]
(Background on this error at: https://sqlalche.me/e/14/9h9h)
api.py:34 - 2024-08-30 23:36:41,395 - ERROR - Error while user registration UserManagement.get_all_users() missing 1 required positional argument: 'db'
api.py:34 - 2024-08-30 23:36:41,395 - ERROR - Error while user registration UserManagement.get_all_users() missing 1 required positional argument: 'db'
service.py:22 - 2024-09-02 12:57:48,745 - INFO - Register user successfully {'id': UUID('6180fcc8-b981-4217-9306-d6c1feb14253'), 'username': 'aniketbhudke', 'firstname': 'Aniket', 'lastname': 'Bhudke', 'email': 'ab@12.com', 'phone_no': '21903478547', 'password': '@niket', 'is_logged_in': True}
service.py:22 - 2024-09-02 12:57:48,745 - INFO - Register user successfully {'id': UUID('6180fcc8-b981-4217-9306-d6c1feb14253'), 'username': 'aniketbhudke', 'firstname': 'Aniket', 'lastname': 'Bhudke', 'email': 'ab@12.com', 'phone_no': '21903478547', 'password': '@niket', 'is_logged_in': True}
service.py:35 - 2024-09-05 18:21:21,397 - ERROR - Error : SQL expression for WHERE/HAVING role expected, got <class 'src.authentication.auth_models.model.User'>.
service.py:35 - 2024-09-05 18:21:21,397 - ERROR - Error : SQL expression for WHERE/HAVING role expected, got <class 'src.authentication.auth_models.model.User'>.
service.py:35 - 2024-09-07 09:42:31,978 - ERROR - Error : SQL expression for WHERE/HAVING role expected, got <class 'src.authentication.auth_models.model.User'>.
service.py:35 - 2024-09-07 09:42:31,978 - ERROR - Error : SQL expression for WHERE/HAVING role expected, got <class 'src.authentication.auth_models.model.User'>.
service.py:35 - 2024-09-07 09:43:53,969 - ERROR - Error : 'Query' object has no attribute 'WHERE'
service.py:35 - 2024-09-07 09:43:53,969 - ERROR - Error : 'Query' object has no attribute 'WHERE'
service.py:31 - 2024-09-07 09:44:35,243 - INFO - Register user successfully {'id': UUID('25bb6e09-f0f7-42fb-ab8f-1f242377f17e'), 'username': 'kunalaswar', 'firstname': 'Kunal', 'lastname': 'Aswar', 'email': 'ku@aswar.com', 'phone_no': '12312312', 'password': 'kun@l', 'is_logged_in': True}
service.py:31 - 2024-09-07 09:44:35,243 - INFO - Register user successfully {'id': UUID('25bb6e09-f0f7-42fb-ab8f-1f242377f17e'), 'username': 'kunalaswar', 'firstname': 'Kunal', 'lastname': 'Aswar', 'email': 'ku@aswar.com', 'phone_no': '12312312', 'password': 'kun@l', 'is_logged_in': True}
service.py:35 - 2024-09-07 09:45:52,384 - ERROR - Error : SQL expression for WHERE/HAVING role expected, got <class 'src.authentication.auth_models.model.User'>.
service.py:35 - 2024-09-07 09:45:52,384 - ERROR - Error : SQL expression for WHERE/HAVING role expected, got <class 'src.authentication.auth_models.model.User'>.
service.py:31 - 2024-09-07 09:48:26,143 - INFO - Register user successfully {'id': UUID('21e59f5e-6f16-4ed0-8b53-636698eb7e3d'), 'username': 'prathamesh', 'firstname': 'Pratham', 'lastname': 'Rand', 'email': 'p@ande.com', 'phone_no': '12312312', 'password': 'teja', 'is_logged_in': True}
service.py:31 - 2024-09-07 09:48:26,143 - INFO - Register user successfully {'id': UUID('21e59f5e-6f16-4ed0-8b53-636698eb7e3d'), 'username': 'prathamesh', 'firstname': 'Pratham', 'lastname': 'Rand', 'email': 'p@ande.com', 'phone_no': '12312312', 'password': 'teja', 'is_logged_in': True}
service.py:55 - 2024-09-08 13:48:32,151 - ERROR - Error : (builtins.TypeError) Not a boolean value: 'True'
[SQL: UPDATE "user" SET is_logged_in=%(is_logged_in)s WHERE "user".username = %(username_1)s]
[parameters: [{}]]
service.py:55 - 2024-09-08 13:48:32,151 - ERROR - Error : (builtins.TypeError) Not a boolean value: 'True'
[SQL: UPDATE "user" SET is_logged_in=%(is_logged_in)s WHERE "user".username = %(username_1)s]
[parameters: [{}]]
service.py:55 - 2024-09-08 13:57:19,393 - ERROR - Error : type object 'UserDAO' has no attribute 'get_user_by_user_name'
service.py:55 - 2024-09-08 13:57:19,393 - ERROR - Error : type object 'UserDAO' has no attribute 'get_user_by_user_name'
service.py:55 - 2024-09-08 13:57:33,832 - ERROR - Error : type object 'UserDAO' has no attribute 'get_user_by_username'
service.py:55 - 2024-09-08 13:57:33,832 - ERROR - Error : type object 'UserDAO' has no attribute 'get_user_by_username'
service.py:55 - 2024-09-08 13:57:35,021 - ERROR - Error : type object 'UserDAO' has no attribute 'get_user_by_username'
service.py:55 - 2024-09-08 13:57:35,021 - ERROR - Error : type object 'UserDAO' has no attribute 'get_user_by_username'
service.py:32 - 2024-09-12 15:14:37,916 - INFO - Register user successfully {'id': UUID('8f34d0e3-d192-4004-b13d-276594ea7c59'), 'username': 'hk', 'firstname': 'string', 'lastname': 'string', 'email': 'user@example.com', 'phone_no': 'string', 'password': 'string', 'is_logged_in': True}
service.py:32 - 2024-09-12 15:14:37,916 - INFO - Register user successfully {'id': UUID('8f34d0e3-d192-4004-b13d-276594ea7c59'), 'username': 'hk', 'firstname': 'string', 'lastname': 'string', 'email': 'user@example.com', 'phone_no': 'string', 'password': 'string', 'is_logged_in': True}
service.py:51 - 2024-09-12 15:21:19,249 - INFO - harshalkharabe is logging successfully
service.py:51 - 2024-09-12 15:21:19,249 - INFO - harshalkharabe is logging successfully
api.py:49 - 2024-09-12 21:37:57,775 - ERROR - Error in login_for_access_token type object 'UserDAO' has no attribute 'find_user_by_username'
api.py:49 - 2024-09-12 21:37:57,775 - ERROR - Error in login_for_access_token type object 'UserDAO' has no attribute 'find_user_by_username'
api.py:49 - 2024-09-12 21:38:06,275 - ERROR - Error in login_for_access_token type object 'UserDAO' has no attribute 'find_user_by_username'
api.py:49 - 2024-09-12 21:38:06,275 - ERROR - Error in login_for_access_token type object 'UserDAO' has no attribute 'find_user_by_username'
api.py:49 - 2024-09-12 21:38:12,602 - ERROR - Error in login_for_access_token type object 'UserDAO' has no attribute 'find_user_by_username'
api.py:49 - 2024-09-12 21:38:12,602 - ERROR - Error in login_for_access_token type object 'UserDAO' has no attribute 'find_user_by_username'
api.py:49 - 2024-09-12 21:39:01,783 - ERROR - Error in login_for_access_token UserDAO.find_user_by_username() missing 1 required positional argument: 'db'
api.py:49 - 2024-09-12 21:39:01,783 - ERROR - Error in login_for_access_token UserDAO.find_user_by_username() missing 1 required positional argument: 'db'
api.py:49 - 2024-09-12 21:40:08,380 - ERROR - Error in login_for_access_token UserDAO.update_user_login_status() missing 1 required positional argument: 'db'
api.py:49 - 2024-09-12 21:40:08,380 - ERROR - Error in login_for_access_token UserDAO.update_user_login_status() missing 1 required positional argument: 'db'
api.py:49 - 2024-09-12 21:41:22,338 - ERROR - Error in login_for_access_token (builtins.TypeError) Not a boolean value: 'Yes'
[SQL: UPDATE "user" SET is_logged_in=%(is_logged_in)s WHERE "user".username = %(username_1)s]
[parameters: [{}]]
api.py:49 - 2024-09-12 21:41:22,338 - ERROR - Error in login_for_access_token (builtins.TypeError) Not a boolean value: 'Yes'
[SQL: UPDATE "user" SET is_logged_in=%(is_logged_in)s WHERE "user".username = %(username_1)s]
[parameters: [{}]]
api.py:49 - 2024-09-12 21:42:17,059 - ERROR - Error in login_for_access_token 
api.py:49 - 2024-09-12 21:42:17,059 - ERROR - Error in login_for_access_token 
api.py:49 - 2024-09-12 21:43:54,560 - ERROR - Error in login_for_access_token 
api.py:49 - 2024-09-12 21:43:54,560 - ERROR - Error in login_for_access_token 
api.py:49 - 2024-09-12 21:44:48,959 - ERROR - Error in login_for_access_token 
api.py:49 - 2024-09-12 21:44:48,959 - ERROR - Error in login_for_access_token 
api.py:49 - 2024-09-12 21:45:05,325 - ERROR - Error in login_for_access_token 
api.py:49 - 2024-09-12 21:45:05,325 - ERROR - Error in login_for_access_token 
api.py:49 - 2024-09-12 21:46:44,244 - ERROR - Error in login_for_access_token 
api.py:49 - 2024-09-12 21:46:44,244 - ERROR - Error in login_for_access_token 
api.py:49 - 2024-09-12 21:48:23,397 - ERROR - Error in login_for_access_token 
api.py:49 - 2024-09-12 21:48:23,397 - ERROR - Error in login_for_access_token 
api.py:49 - 2024-09-12 21:48:56,869 - ERROR - Error in login_for_access_token 
api.py:49 - 2024-09-12 21:48:56,869 - ERROR - Error in login_for_access_token 
api.py:49 - 2024-09-12 21:49:17,562 - ERROR - Error in login_for_access_token 
api.py:49 - 2024-09-12 21:49:17,562 - ERROR - Error in login_for_access_token 
api.py:46 - 2024-09-12 21:50:39,213 - INFO - User sagardhok logged in.
api.py:46 - 2024-09-12 21:50:39,213 - INFO - User sagardhok logged in.
api.py:49 - 2024-09-12 21:51:02,304 - ERROR - Error in login_for_access_token 
api.py:49 - 2024-09-12 21:51:02,304 - ERROR - Error in login_for_access_token 
api.py:46 - 2024-09-12 21:51:12,974 - INFO - User harshalkharabe logged in.
api.py:46 - 2024-09-12 21:51:12,974 - INFO - User harshalkharabe logged in.
api.py:46 - 2024-09-12 21:53:02,604 - INFO - User sagardhok logged in.
api.py:46 - 2024-09-12 21:53:02,604 - INFO - User sagardhok logged in.
api.py:52 - 2024-09-12 21:55:25,977 - INFO - User sagardhok logged in.
api.py:52 - 2024-09-12 21:55:25,977 - INFO - User sagardhok logged in.
api.py:52 - 2024-09-12 21:55:35,143 - INFO - User sagardhok logged in.
api.py:52 - 2024-09-12 21:55:35,143 - INFO - User sagardhok logged in.
api.py:52 - 2024-09-12 21:55:55,917 - INFO - User aniketbhudke logged in.
api.py:52 - 2024-09-12 21:55:55,917 - INFO - User aniketbhudke logged in.
api.py:55 - 2024-09-12 21:56:02,137 - ERROR - Error in login_for_access_token 
api.py:55 - 2024-09-12 21:56:02,137 - ERROR - Error in login_for_access_token 
api.py:52 - 2024-09-12 21:56:08,127 - INFO - User sagardhok logged in.
api.py:52 - 2024-09-12 21:56:08,127 - INFO - User sagardhok logged in.
api.py:50 - 2024-09-12 21:57:13,288 - INFO - User sagardhok logged in.
api.py:50 - 2024-09-12 21:57:13,288 - INFO - User sagardhok logged in.
api.py:51 - 2024-09-15 21:31:43,175 - INFO - User sagardhok logged in.
api.py:51 - 2024-09-15 21:31:43,175 - INFO - User sagardhok logged in.
api.py:51 - 2024-09-15 21:36:16,834 - INFO - User sagardhok logged in.
api.py:51 - 2024-09-15 21:36:16,834 - INFO - User sagardhok logged in.
api.py:51 - 2024-09-15 21:38:25,861 - INFO - User sagardhok logged in.
api.py:51 - 2024-09-15 21:38:25,861 - INFO - User sagardhok logged in.
api.py:51 - 2024-09-15 21:42:43,425 - INFO - User harshalkharabe logged in.
api.py:51 - 2024-09-15 21:42:43,425 - INFO - User harshalkharabe logged in.
api.py:51 - 2024-09-15 21:43:08,960 - INFO - User harshalkharabe logged in.
api.py:51 - 2024-09-15 21:43:08,960 - INFO - User harshalkharabe logged in.
api.py:58 - 2024-09-15 21:57:45,908 - INFO - User sagardhok logged in.
api.py:58 - 2024-09-15 21:57:45,908 - INFO - User sagardhok logged in.
